language: vala
compiler:
  - vala
  - gcc
before_install:
  - sudo apt-get update -qq -y
  - sudo apt-get install cmake valac libgee-0.8-dev -y
script: mkdir build && cd build && cmake .. && make && sudo make install && sudo ldconfig
notifications:
  irc:
    channels:
      - "irc.freenode.net#canaldev"
    on_success: change
    on_failure: always
    use_notice: true
    skip_join: true
