language: vala
compiler:
  - vala
  - gcc
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install update-manager-core software-properties-common
  - sudo sed -i 's/^\(Prompt=\).*/\1lts/' /etc/update-manager/release-upgrades
  - sudo do-release-upgrade -d -f DistUpgradeViewNonInteractive
  - sudo add-apt-repository -y ppa:inizan-yannick/vala-libs
  - sudo add-apt-repository -y ppa:ricotz/testing
  - sudo apt-get update -qq
  - sudo apt-get install valac-0.24 libgee-0.8-dev libmee-1.0-dev
script: ./autogen.sh && make && sudo make install
notifications:
  irc:
    channels:
      - "irc.freenode.net#canaldev"
    on_success: change
    on_failure: always
    use_notice: true
    skip_join: true
