language: vala
compiler:
  - vala
  - gcc
before_install:
  - sudo apt-get update -qq -y
  - sudo apt-get install update-manager-core software-properties-common -y
  - sudo sed -i 's/^\(Prompt=\).*/\1lts/' /etc/update-manager/release-upgrades
  - sudo do-release-upgrade -d -f DistUpgradeViewNonInteractive
  - sudo apt-get update -qq -y
  - sudo apt-get install valac-0.28
script: ./autogen.sh && make && sudo make install
notifications:
  irc:
    channels:
      - "irc.freenode.net#canaldev"
    on_success: change
    on_failure: always
    use_notice: true
    skip_join: true
